-- CREACION DE BASE DE DATOS -- 
alter session set "_ORACLE_SCRIPT"=true;
CREATE USER HotelesVeranum IDENTIFIED BY hotel
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER HotelesVeranum QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO HotelesVeranum;
GRANT "RESOURCE" TO HotelesVeranum;
ALTER USER HotelesVeranum DEFAULT ROLE "RESOURCE";